import type { ScheduleEvent } from "./types";

/** Full conference catalog with parallel sessions (read-only browse source). */
export const MOCK_CONFERENCE_SCHEDULE: ScheduleEvent[] = [
  {
    id: "conf-talk-keynote",
    type: "talk",
    talkId: 401,
    title: "Keynote: Future of Web Development",
    trackName: "Main Stage",
    start: new Date(2026, 5, 11, 9, 0),
    end: new Date(2026, 5, 11, 10, 0),
  },
  {
    id: "conf-talk-ts6",
    type: "talk",
    talkId: 205,
    title: "TypeScript 6: What's New",
    trackName: "Track 2",
    start: new Date(2026, 5, 11, 9, 0),
    end: new Date(2026, 5, 11, 9, 45),
  },
  {
    id: "conf-break-coffee",
    type: "break",
    title: "Coffee break",
    location: "Lobby",
    start: new Date(2026, 5, 11, 10, 0),
    end: new Date(2026, 5, 11, 10, 30),
  },
  {
    id: "conf-talk-rsc",
    type: "talk",
    talkId: 101,
    title: "React Server Components Deep Dive",
    trackName: "Main Stage",
    start: new Date(2026, 5, 11, 10, 30),
    end: new Date(2026, 5, 11, 11, 15),
  },
  {
    id: "conf-talk-panel",
    type: "talk",
    talkId: 402,
    title: "Panel: State Management in 2026",
    trackName: "Track 2",
    start: new Date(2026, 5, 11, 10, 30),
    end: new Date(2026, 5, 11, 11, 15),
  },
  {
    id: "conf-meeting-mentor",
    type: "meeting",
    title: "1:1 with mentor",
    location: "Mentor lounge",
    start: new Date(2026, 5, 11, 11, 30),
    end: new Date(2026, 5, 11, 12, 0),
  },
  {
    id: "conf-break-lunch",
    type: "break",
    title: "Lunch break",
    location: "Food court",
    start: new Date(2026, 5, 11, 12, 0),
    end: new Date(2026, 5, 11, 13, 0),
  },
  {
    id: "conf-talk-supabase",
    type: "talk",
    talkId: 310,
    title: "Building Real-time Apps with Supabase",
    trackName: "Main Stage",
    start: new Date(2026, 5, 11, 14, 0),
    end: new Date(2026, 5, 11, 14, 45),
  },
  {
    id: "conf-custom-workshop",
    type: "custom",
    title: "Hands-on React workshop",
    description: "Bring your laptop",
    location: "Workshop room",
    start: new Date(2026, 5, 11, 14, 0),
    end: new Date(2026, 5, 11, 15, 30),
  },
  {
    id: "conf-custom-expo",
    type: "custom",
    title: "Expo hall visit",
    location: "Expo hall",
    start: new Date(2026, 5, 11, 15, 45),
    end: new Date(2026, 5, 11, 16, 30),
  },
  {
    id: "conf-break-networking",
    type: "break",
    title: "Networking break",
    location: "Community area",
    start: new Date(2026, 5, 11, 16, 30),
    end: new Date(2026, 5, 11, 17, 0),
  },
  {
    id: "conf-talk-rsc-day2",
    type: "talk",
    talkId: 101,
    title: "React Server Components Deep Dive",
    trackName: "Main Stage",
    start: new Date(2026, 5, 12, 9, 30),
    end: new Date(2026, 5, 12, 10, 15),
  },
  {
    id: "conf-talk-ts6-day2",
    type: "talk",
    talkId: 205,
    title: "TypeScript 6: What's New",
    trackName: "Track 2",
    start: new Date(2026, 5, 12, 9, 30),
    end: new Date(2026, 5, 12, 10, 15),
  },
  {
    id: "conf-custom-lunch-mentors",
    type: "custom",
    title: "Lunch with mentors",
    description: "Informal Q&A over food",
    location: "Restaurant district",
    start: new Date(2026, 5, 12, 12, 0),
    end: new Date(2026, 5, 12, 13, 0),
  },
  {
    id: "conf-talk-supabase-day2",
    type: "talk",
    talkId: 310,
    title: "Building Real-time Apps with Supabase",
    trackName: "Main Stage",
    start: new Date(2026, 5, 12, 15, 30),
    end: new Date(2026, 5, 12, 16, 15),
  },
  {
    id: "conf-talk-panel-day2",
    type: "talk",
    talkId: 402,
    title: "Panel: State Management in 2026",
    trackName: "Track 2",
    start: new Date(2026, 5, 12, 15, 30),
    end: new Date(2026, 5, 12, 16, 15),
  },
  {
    id: "conf-meeting-standup",
    type: "meeting",
    title: "Hackathon team standup",
    location: "Team table 7",
    attendees: ["Jonas", "Team"],
    start: new Date(2026, 5, 13, 9, 0),
    end: new Date(2026, 5, 13, 9, 30),
  },
  {
    id: "conf-break-afternoon",
    type: "break",
    title: "Afternoon break",
    location: "Expo hall",
    start: new Date(2026, 5, 13, 11, 0),
    end: new Date(2026, 5, 13, 11, 30),
  },
  {
    id: "conf-talk-keynote-closing",
    type: "talk",
    talkId: 401,
    title: "Closing Keynote",
    trackName: "Main Stage",
    start: new Date(2026, 5, 13, 16, 0),
    end: new Date(2026, 5, 13, 17, 0),
  },
  {
    id: "conf-custom-networking",
    type: "custom",
    title: "Open networking",
    location: "Community area",
    start: new Date(2026, 5, 13, 16, 0),
    end: new Date(2026, 5, 13, 16, 30),
  },
];

export function isConferenceEventId(id: string): boolean {
  return id.startsWith("conf-");
}
